{
 "title": "Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "layer", "label": "Layer", "query": "MESH" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(service_traffic{layer='$layer'}, service)"
    }
   },
   {
    "name": "service_instance",
    "label": "Service Instance",
    "query": {
     "query": "label_values(instance_traffic{layer='$layer', service='$service'}, service_instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(endpoint_traffic{layer='$layer', service='$service', keyword='$endpoint_keyword', limit='$endpoint_limit'}, endpoint)"
    }
   },
   { "name": "endpoint_keyword", "label": "Endpoint Keyword" },
   { "name": "endpoint_limit", "label": "Endpoint Limit", "query": "20,50,100" },
   { "name": "DS_OAP", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_resp_time{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "service_cpm{service='$service', layer='$layer'} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "service_status_code{service='$service', layer='$layer'} / 60 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_sla{service='$service', layer='$layer'} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Apdex",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_apdex{service='$service', layer='$layer'} / 10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Response Time Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_percentile{service='$service', layer='$layer', labels='0,1,2,3,4', relabels='P50,P75,P90,P95,P99'}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Service 2XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "service_status_code{service='$service', layer='$layer', labels='200'} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 4XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "service_status_code{service='$service', layer='$layer', labels='400'} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service 5XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "service_status_code{service='$service', layer='$layer', labels='500'} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "service_sidecar_internal_req_latency_nanos{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Response)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "service_sidecar_internal_resp_latency_nanos{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Service Instance Load ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "service_instance_cpm{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Instance Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "service_instance_throughput_received{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "service_instance_throughput_sent{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Instance Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_instance_sla{service='$service', service_instance='$service_instance', layer='$layer'} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_instance_resp_time{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Endpoint Load ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "endpoint_cpm{service='$service', endpoint='$endpoint', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "endpoint_sidecar_internal_req_latency_nanos{service='$service', endpoint='$endpoint', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "endpoint_sla{service='$service', endpoint='$endpoint', layer='$layer'} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Response Time Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "endpoint_percentile{service='$service', endpoint=\"$endpoint\", layer='$layer', labels='0,1,2,3,4', relabels='P50,P75,P90,P95,P99'}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Response)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "endpoint_sidecar_internal_resp_latency_nanos{service='$service', endpoint='$endpoint', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Envoy Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Heap Memory Used ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "envoy_memory_allocated_max{service='$service', service_instance='$service_instance',layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_heap_memory_used{service='$service', service_instance='$service_instance',layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_memory_allocated{service='$service', service_instance='$service_instance',layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_memory_physical_size{service='$service', service_instance='$service_instance',layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_memory_physical_size_max{service='$service', service_instance='$service_instance',layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_heap_memory_max_used{service='$service', service_instance='$service_instance',layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_total_connections_used{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_parent_connections_used{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_worker_threads_max{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_worker_threads{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy Bug Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_bug_failures{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "service_instance_sidecar_internal_req_latency_nanos{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Response)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "service_instance_sidecar_internal_resp_latency_nanos{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}